default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: addressbook

  
test:
  <<: *default
  database: myapp_test


production:
  <<: *default
  database: addressbook
  # username: rich
  # password: <%= ENV['ADDRESSBOOK_PASSWORD'] %>
